CREATE TABLE car
    (id bigint NOT NULL PRIMARY KEY,
	brand CHARACTER VARYING(255) NOT NULL,
	model CHARACTER VARYING(255) NOT NULL,
	cost MONEY)

CREATE TABLE man
    (id bigint NOT NULL PRIMARY KEY,
	name CHARACTER VARYING(255) UNIQUE NOT NULL,
	age INTEGER NOT NULL CHECK (age > 0),
	license BOOLEAN,
	car_id bigint REFERENCES car (id))